### ISSUE TITLE
Незалогиненному юзеру показывают фильтр «Понравившиеся мне»

### ISSUE THREAD

**Issue by levenkov** [crags-app/gekkon#28]
Хотя если ты не залогинен, то у тебя априори не может быть лайкнутых трасс.

**Comment by SvetlanaBatova** [comment]
https://github.com/bitia-ru/gekkon-frontend/pull/227 десктоп
В мобильном незалогиненному юзеру показываются все фильтры:
https://github.com/bitia-ru/gekkon-m-frontend/pull/139 мобильник
