### ISSUE TITLE
Брать дату пролаза при добавлении пролаза из даты в фильтрах на схеме зала

### ISSUE THREAD

**Issue by levenkov** [crags-app/gekkon#33]
Сейчас берется текущая дата. Если мы открыли окно добавления пролаза из схемы зала (а не карточек/таблицы), то вместо текущей даты брать дату из фильтров (ту дату, на которую показаны трассы на схеме).

Для не-схемы зала в случае, если трасса уже скручена, датой пролаза брать последний день активности трассы.

Подумать, можно ли добавить валидацию на уровне БД, препятствующую добавлению пролаза на дату, когда трассы не была активна.

Если в процессе добавления пролазов изменили дату последнего пролаза, то, как и сейчас, новый даты пролазов добавляем с той же датой, что и последний пролаз. Но сейчас это справедливо даже в случае перезагрузки страницы или повторного открытия окна пролазов, что приводит к проблеме: когда несколько тренировок подряд лазаешь трассу, то кроме первого дня всегда приходится редактировать дату, т.к. добавляемый пролаз проставляется в дату с предыдущей тренировки. Кажется, что это решается таким образом: при редактировании даты пролаза, если он последний в списке, сохраняем эту дату в состояние окна. Так, чтобы при перезагрузке или ухода из окна это состояние сбрасывалось. Если добавляем пролаз и в состоянии есть сохраненная дата — используем её. Нет сохранённой — применяем логику, описанную выше (дата из фильтра, дата последнего дня активности трассы или текущая дата).

**Comment by SvetlanaBatova** [comment]
Насчет валидации на уровне БД:
Есть вариант перенести history из пролазов в отдельную таблицу, тогда accomplished_at можно будет хранить в отдельной колонке таблицы и типом дата. В этом случае можно написать триггер, который будет на insert/update таблицы history проверять валидность дат. Такой вариант должен быть лучше, чем работа с history в формате json, т.к. здесь не будет каста в дату, который необходим для сравнения дат друг с другом и должен работать быстрее, так как не надо парсить json и проходить по нему циклом

**Comment by levenkov** [comment]
Особые кейсы для тестирования:

1. Открываем уже скрученную некоторое время назад трассу через схему зала (т.е. должна быть выбрана не текущая дата). Редактируем дату скрутки, меняем её так, чтобы к выбранной на схеме зала дате трасса уже оказалась скрученной. И добавляем пролаз. Датой должна оказаться дата скрутки трассы, а не выбранная на схеме дата.
