### ISSUE TITLE
Клавиши вправо-влево на трассе мешают написанию комментария

### ISSUE THREAD

**Issue by levenkov** [crags-app/gekkon#34]
В процессе написания комментария, если нажать на стрелочку влево или вправо, происходит переключение просматриваемой трассы.

Ожидаемое поведение: просто курсор должен передвигаться в поле ввода.

**Comment by SvetlanaBatova** [comment]
https://github.com/bitia-ru/gekkon-frontend/pull/221

**Comment by Evgeniya-K** [comment]
исправлено
