### ISSUE TITLE
При входе через Vk игнорируется чек-бокс "запомнить меня"

### ISSUE THREAD

**Issue by levenkov** [crags-app/gekkon#41]
Длительность сессии получается равной одним суткам вне зависимости от состояния чек-бокса.

**Comment by SvetlanaBatova** [comment]
https://github.com/bitia-ru/gekkon-backend/pull/139 бекенд
https://github.com/bitia-ru/gekkon-frontend/pull/261 фронт

Аналогичные правки нужны для мобильной версии
