### ISSUE TITLE
Обновлять схему зала после добавления трассы

### ISSUE THREAD

**Issue by KataevAS** [crags-app/gekkon#44]
Сейчас, при сохранении новой трассы, кружок трассы на схеме зала не появляется без обновления страницы, либо пока пользователь не выйдет и не зайдет в модалку добавления заново, что бы отправить запрос на routes.

**Comment by SvetlanaBatova** [comment]
https://github.com/bitia-ru/gekkon-frontend/pull/251 десктоп
